name: dynamics
channels:
  - conda-forge
  - defaults
dependencies:
  - brotlipy=0.7.0
  - ca-certificates=2022.4.26
  - certifi=2022.6.15
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - colorama=0.4.5
  - conda=4.13.0
  - conda-content-trust=0.1.1
  - conda-package-handling=1.8.1
  - console_shortcut=0.1.1
  - cryptography=37.0.1
  - idna=3.3
  - jupyter
  - jupyterlab=3.4.3
  - matplotlib=3.5.2
  - nodejs=18.6.0
  - notebook=6.4.11
  - numpy=1.23.1
  - openssl=1.1.1q
  - pip=22.1.2
  - plotly=5.9.0
  - pycosat=0.6.3
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.12
  - pywin32=302
  - requests=2.28.1
  - ruamel_yaml=0.15.100
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.5
  - tqdm=4.64.0
  - tzdata=2022a
  - urllib3=1.26.9
  - wheel=0.37.1
  - xarray=2022.3.0
  - yaml=0.2.5